#!/usr/bin/env python3
"""
Insurance Advisor AgentCore - CDK Application Entry Point
Deploys authentication, tools, and AgentCore infrastructure
"""
import aws_cdk as cdk
from cdk.auth_stack import AuthStack
from cdk.tools_stack import ToolsStack
from cdk.agentcore_stack import AgentCoreStack
from cdk.voice_stack import VoiceStack
from cdk.frontend_stack import FrontendStack
from pathlib import Path
# CDK NAG imports
from aws_cdk import Aspects
import cdk_nag
from cdk_nag import NagSuppressions

# Initialize CDK app
app = cdk.App()

# Deploy stacks in order with dependencies
auth_stack = AuthStack(app, "insadv-01-auth")
tools_stack = ToolsStack(app, "insadv-02-tools", auth_stack=auth_stack)
agentcore_stack = AgentCoreStack(app, "insadv-03-agentcore", 
                                auth_stack=auth_stack, 
                                tools_stack=tools_stack)
voice_stack = VoiceStack(app, "insadv-04-voice",
                         auth_stack=auth_stack,
                         agentcore_stack=agentcore_stack)

# Frontend stack is only synthesized after the React app has been built
# (deploy.sh handles the ordering: backend stacks → npm build → frontend stack).
# Skipping it on a cold synth keeps `cdk deploy insadv-01-auth` etc. usable
# before any frontend build exists.
react_dist = Path("react-frontend/dist")
frontend_stack = None
if react_dist.exists() and any(react_dist.iterdir()):
    frontend_stack = FrontendStack(app, "insadv-05-frontend")

# CDK NAG configuration
Aspects.of(app).add(cdk_nag.AwsSolutionsChecks(verbose=True))

# =================================================================
# CDK NAG SUPPRESSIONS (consolidated)
# =================================================================

# --- Auth Stack ---
NagSuppressions.add_resource_suppressions(
    auth_stack.user_pool,
    [
        {"id": "AwsSolutions-COG3", "reason": "Advanced Security Mode requires Plus feature plan which is not needed for this demo - UserPool"},
        {"id": "AwsSolutions-COG2", "reason": "MFA intentionally disabled for demo ease of use - UserPool"},
    ]
)
NagSuppressions.add_resource_suppressions(
    auth_stack.gateway_pool,
    [
        {"id": "AwsSolutions-COG3", "reason": "Advanced Security Mode requires Plus feature plan which is not needed for this demo - GatewayPool"},
        {"id": "AwsSolutions-COG2", "reason": "MFA not applicable - GatewayPool is for service-to-service auth with no human users"},
    ]
)

# --- Tools Stack ---
NagSuppressions.add_resource_suppressions(
    tools_stack.access_log_bucket,
    [{"id": "AwsSolutions-S1", "reason": "This is the server access log bucket itself - enabling access logs on it would create an infinite loop"}]
)

# CDK-managed internal roles - runtime/policies not directly controllable
for stack in [auth_stack, tools_stack, agentcore_stack, voice_stack]:
    NagSuppressions.add_stack_suppressions(stack, [
        {"id": "AwsSolutions-IAM4", "reason": "AWS managed policy attached by CDK-managed constructs (AwsCustomResource, BucketDeployment, Lambda Function service roles) - not directly controllable",
         "applies_to": ["Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]}
    ])

# --- Tools Stack: CDK-managed grant wildcards ---
NagSuppressions.add_stack_suppressions(tools_stack, [
    {"id": "AwsSolutions-IAM5", "reason": "Wildcard permissions generated by CDK grant_read/grant_read_write_data/BucketDeployment constructs - not directly controllable",
     "applies_to": [
         "Action::s3:GetBucket*", "Action::s3:GetObject*", "Action::s3:List*",
         "Action::s3:Abort*", "Action::s3:DeleteObject*",
         "Resource::arn:<AWS::Partition>:s3:::cdk-hnb659fds-assets-<AWS::AccountId>-<AWS::Region>/*",
         "Resource::<PortfolioBucketCEAA46CF.Arn>/*",
         "Resource::<PromotionBucket9C5C2113.Arn>/*",
         "Resource::<ProfilesTable3B48B4C6.Arn>/index/*",
         "Resource::<PoliciesTableB128A423.Arn>/index/*",
     ]},
    {"id": "AwsSolutions-IAM5", "reason": "MockDataCustomResourceRole needs /aws/lambda/* because CDK auto-generates the Lambda function name",
     "applies_to": ["Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/lambda/*"]},
])

NagSuppressions.add_resource_suppressions(
    tools_stack.api,
    [{"id": "AwsSolutions-APIG2", "reason": "Request validation is enabled on all API methods via RequestValidator - CDK Nag does not detect validators attached at method level"}]
)

# Public sign-up endpoint cannot be authenticated by definition. WAFv2 with
# the AWS managed common rule set is associated with the API Gateway and
# provides baseline abuse protection. Targeted at just the /signup resource
# so the rules still apply to the rest of the API.
NagSuppressions.add_resource_suppressions_by_path(
    tools_stack,
    "/insadv-02-tools/InsuranceAdvisorApi/Default/signup/POST/Resource",
    [
        {"id": "AwsSolutions-APIG4",
         "reason": "Public sign-up endpoint is unauthenticated by design. The Cognito user pool is configured with AllowAdminCreateUserOnly via an org policy, so we cannot use Cognito self-service signup. Backend Lambda creates the user via admin APIs after validating the request. WAFv2 protects the endpoint."},
        {"id": "AwsSolutions-COG4",
         "reason": "Public sign-up endpoint is unauthenticated by design - the user does not yet exist in the Cognito pool when calling /signup."},
    ],
)

# --- AgentCore Stack: service-level wildcards ---
NagSuppressions.add_stack_suppressions(agentcore_stack, [
    {"id": "AwsSolutions-IAM5", "reason": "CloudWatch PutMetricData and X-Ray APIs do not support resource-level permissions - wildcard resource required",
     "applies_to": ["Resource::*"]},
    {"id": "AwsSolutions-IAM5", "reason": "bedrock-agentcore:* action required for AgentCore Runtime and custom resource to manage runtime lifecycle",
     "applies_to": ["Action::bedrock-agentcore:*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Log group wildcard needed to cover log streams within the specific log group prefix",
     "applies_to": [
         "Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/bedrock-agentcore/gateways/insurance-advisor-gateway*",
         "Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/bedrock-agentcore/runtimes/insurance_advisor_runtime*",
     ]},
    {"id": "AwsSolutions-IAM5", "reason": "Workload identity wildcard required to access any workload identity in the default directory",
     "applies_to": ["Resource::arn:aws:bedrock-agentcore:<AWS::Region>:<AWS::AccountId>:workload-identity-directory/default/workload-identity/*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Token vault sub-resource wildcard required for AgentCore Identity to resolve OAuth2 credential providers registered in the default vault",
     "applies_to": [
         "Resource::arn:aws:bedrock-agentcore:<AWS::Region>:<AWS::AccountId>:token-vault/default/*",
         "Resource::arn:aws:bedrock-agentcore:<AWS::Region>:<AWS::AccountId>:token-vault/default/oauth2credentialprovider/*",
     ]},
    {"id": "AwsSolutions-IAM5", "reason": "AgentCore Identity manages its own secrets under the bedrock-agentcore-identity!default/oauth2/ namespace with unpredictable suffixes; wildcard is required for IAM delegation when the Token Vault reads secrets on behalf of the runtime role",
     "applies_to": ["Resource::arn:aws:secretsmanager:<AWS::Region>:<AWS::AccountId>:secret:bedrock-agentcore-identity!default/oauth2/*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Gateway sub-resource wildcard required to access gateway targets",
     "applies_to": ["Resource::arn:aws:bedrock-agentcore:<AWS::Region>:<AWS::AccountId>:gateway/<InsuranceAdvisorGateway066E037D.GatewayIdentifier>/*"]},
    {"id": "AwsSolutions-IAM5", "reason": "CDK alpha module adds :* suffix to Lambda ARNs for invoke grants",
     "applies_to": ["Resource::<PortfolioLambda015C4EC4.Arn>:*", "Resource::<PromotionsLambda491A7234.Arn>:*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Log group ARN :* suffix required by CloudWatch Logs for log stream access",
     "applies_to": ["Resource::<ApiGatewayOAuthProviderOAuth2ProviderLogGroupDBF77067.Arn>:*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Service-linked role ARN uses account wildcard as required by AWS",
     "applies_to": ["Resource::arn:aws:iam::*:role/aws-service-role/runtime-identity.bedrock-agentcore.amazonaws.com/AWSServiceRoleForBedrockAgentCoreRuntimeIdentity"]},
])

# CDK-managed internal Lambdas (AwsCustomResource/BucketDeployment) - runtime not controllable
NagSuppressions.add_stack_suppressions(auth_stack, [
    {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK AwsCustomResource construct and cannot be directly controlled", "applies_to": ["*AWS679f53fac002430cb0da5b7982bd2287*"]}
])
NagSuppressions.add_stack_suppressions(tools_stack, [
    {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK BucketDeployment/AwsCustomResource construct and cannot be directly controlled"}
])
NagSuppressions.add_stack_suppressions(agentcore_stack, [
    {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK AwsCustomResource construct and cannot be directly controlled"}
])

# --- Voice Stack: same AgentCore service-level wildcards as main runtime ---
NagSuppressions.add_stack_suppressions(voice_stack, [
    {"id": "AwsSolutions-IAM5", "reason": "CloudWatch/X-Ray APIs do not support resource-level permissions",
     "applies_to": ["Resource::*"]},
    {"id": "AwsSolutions-IAM5", "reason": "bedrock-agentcore:* required for runtime custom resource lifecycle",
     "applies_to": ["Action::bedrock-agentcore:*"]},
    {"id": "AwsSolutions-IAM5", "reason": "Log group wildcard needed for log streams in the voice runtime log group",
     "applies_to": [
         "Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/bedrock-agentcore/runtimes/insurance_voice_runtime*",
     ]},
    {"id": "AwsSolutions-IAM5", "reason": "Service-linked role ARN uses account wildcard as required by AWS",
     "applies_to": ["Resource::arn:aws:iam::*:role/aws-service-role/runtime-identity.bedrock-agentcore.amazonaws.com/AWSServiceRoleForBedrockAgentCoreRuntimeIdentity"]},
    {"id": "AwsSolutions-IAM5", "reason": "InvokeAgentRuntime requires sub-resource wildcard for qualifiers/endpoints",
     "applies_to": [
         "Resource::<insadv03agentcoreInsuranceAdvisorRuntimeAgentRuntimeF05FDDC2.Ref>/*",
     ]},
    {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK AwsCustomResource construct and cannot be directly controlled"},
])

# --- Frontend Stack: S3 + CloudFront for the React app ---
if frontend_stack is not None:
    NagSuppressions.add_stack_suppressions(frontend_stack, [
        {"id": "AwsSolutions-IAM4", "reason": "AWS managed policy attached by CDK-managed BucketDeployment Lambda - not directly controllable",
         "applies_to": ["Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]},
        {"id": "AwsSolutions-IAM5", "reason": "Wildcard permissions generated by CDK BucketDeployment construct (s3:GetBucket*, s3:GetObject*, s3:List*, s3:Abort*, s3:DeleteObject*, CloudFront CreateInvalidation on the distribution) - not directly controllable",
         "applies_to": [
             "Action::s3:GetBucket*", "Action::s3:GetObject*", "Action::s3:List*",
             "Action::s3:Abort*", "Action::s3:DeleteObject*",
             "Resource::arn:<AWS::Partition>:s3:::cdk-hnb659fds-assets-<AWS::AccountId>-<AWS::Region>/*",
             "Resource::<SiteBucket397A1860.Arn>/*",
         ]},
        {"id": "AwsSolutions-IAM5", "reason": "BucketDeployment custom resource Lambda needs /aws/lambda/* because CDK auto-generates the function name",
         "applies_to": ["Resource::arn:<AWS::Partition>:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/lambda/*"]},
        {"id": "AwsSolutions-L1", "reason": "Lambda runtime is managed by CDK BucketDeployment construct and cannot be directly controlled"},
        # Server access logs on the access-log buckets themselves would loop,
        # so they are intentionally not configured.
        {"id": "AwsSolutions-S1", "reason": "Server access log destination buckets cannot themselves enable access logs without creating an infinite loop"},
        # CloudFront-specific
        {"id": "AwsSolutions-CFR1", "reason": "Geo restrictions are not required for this internal demo / advisor portal"},
        {"id": "AwsSolutions-CFR2", "reason": "WAF is not attached to CloudFront for this demo. The React app is a static SPA; the API Gateway it calls is already protected by AWS WAFv2 (see ToolsStack) and Cognito JWT authorization"},
        {"id": "AwsSolutions-CFR3", "reason": "CloudFront access logging is enabled to a dedicated log bucket - CDK Nag false positive when log_bucket is set via the L2 Distribution construct"},
        {"id": "AwsSolutions-CFR4", "reason": "Distribution uses the default CloudFront domain (*.cloudfront.net), which only supports the default certificate. Custom domain + ACM cert is out of scope for this demo"},
        {"id": "AwsSolutions-CFR7", "reason": "Origin Access Control (OAC) is used via S3BucketOrigin.with_origin_access_control - CDK Nag false positive that does not detect the new OAC construct"},
    ])

# Synthesize CloudFormation templates
app.synth()
