import { fetchAuthSession } from 'aws-amplify/auth';

import type {
  CatalogProduct,
  ComparisonResponse,
  Customer,
  Policy,
  RecommendationResponse,
} from '../types';

async function authHeaders(): Promise<Record<string, string>> {
  const session = await fetchAuthSession();
  const token = session.tokens?.accessToken?.toString();
  if (!token) {
    throw new Error('Not authenticated');
  }
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
}

function apiUrl(endpoint: string): string {
  const base = import.meta.env.VITE_API_BASE_URL.replace(/\/$/, '');
  return `${base}/${endpoint.replace(/^\//, '')}`;
}

async function getJson<T>(endpoint: string): Promise<T> {
  const response = await fetch(apiUrl(endpoint), { headers: await authHeaders() });
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`${endpoint} returned ${response.status}: ${body}`);
  }
  return (await response.json()) as T;
}

async function postJson<T>(endpoint: string, payload: unknown): Promise<T> {
  const response = await fetch(apiUrl(endpoint), {
    method: 'POST',
    headers: await authHeaders(),
    body: JSON.stringify(payload),
  });
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`${endpoint} returned ${response.status}: ${body}`);
  }
  return (await response.json()) as T;
}

/**
 * Fetch customers assigned to the authenticated advisor and join them with
 * their policies client-side. Joins customer profiles with their policies client-side.
 */
export async function loadCustomersWithPolicies(): Promise<Customer[]> {
  const [customers, policies] = await Promise.all([
    getJson<Omit<Customer, 'policies'>[]>('profile'),
    getJson<Policy[]>('policy'),
  ]);

  return customers.map((c) => ({
    ...c,
    policies: policies.filter((p) => p.customer_id === c.customer_id),
  }));
}

/** Coerce a DynamoDB-stringified numeric to a number for display. */
export function toNumber(value: number | string | undefined): number {
  if (value === undefined || value === null) return 0;
  if (typeof value === 'number') return value;
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

/** Distinct product types present in the catalog, sorted. */
export async function loadProductTypes(): Promise<string[]> {
  const data = await getJson<{ product_types: string[] }>('catalog/product-types');
  return data.product_types;
}

/** Catalog entries filtered to a single product type. */
export async function loadProductsByType(productType: string): Promise<CatalogProduct[]> {
  const qs = new URLSearchParams({ type: productType }).toString();
  const data = await getJson<{ products: CatalogProduct[] }>(`catalog/products?${qs}`);
  return data.products;
}

/**
 * Produce a side-by-side comparison of 2-4 products. Response is a fixed
 * JSON shape generated by the LLM; see `ComparisonResponse` in types.ts.
 * Translated into the active UI locale by the backend.
 */
export async function compareProducts(
  productIds: string[],
  locale: string
): Promise<ComparisonResponse> {
  return postJson<ComparisonResponse>('comparator/compare', {
    product_ids: productIds,
    locale,
  });
}

/**
 * Generate an LLM-backed coverage-gap analysis + Unicorn product
 * recommendation for the selected customer. Pulls the customer's full
 * context server-side (profile + policies + catalog + promotions). Returns
 * a structured payload — see RecommendationResponse for the exact shape.
 *
 * Latency is dominated by the Bedrock call, typically 4-8 seconds. Callers
 * should render a loading state while this is in flight.
 */
export async function loadRecommendation(
  customerId: string,
  locale: string
): Promise<RecommendationResponse> {
  return postJson<RecommendationResponse>('recommend', {
    customer_id: customerId,
    locale,
  });
}

/**
 * Public sign-up. Calls the unauthenticated POST /signup Lambda which uses
 * Cognito admin APIs to create + confirm the user, working around the
 * org-policy that forces AllowAdminCreateUserOnly back to True on the pool.
 *
 * Throws an Error with the server-supplied message on failure (e.g. user
 * already exists, weak password). On success, the caller can sign in with
 * the same credentials immediately — the user is already CONFIRMED.
 */
export async function signupUser(email: string, password: string): Promise<void> {
  const response = await fetch(apiUrl('signup'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  if (!response.ok) {
    let message = `Sign-up failed (${response.status})`;
    try {
      const body = (await response.json()) as { error?: string };
      if (body?.error) message = body.error;
    } catch {
      /* ignore JSON parse errors, use default */
    }
    throw new Error(message);
  }
}

/**
 * Allowed Content-Type → file extension mapping. Mirror of the server-side
 * allowlist in lambda/documents/index.py. Anything else is rejected
 * client-side with a friendly error.
 */
const ALLOWED_DOC_CONTENT_TYPES: Record<string, string> = {
  'application/pdf': 'pdf',
  'text/markdown': 'md',
  'text/plain': 'txt',
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};

const MAX_DOC_SIZE_BYTES = 10 * 1024 * 1024; // 10 MB — must match server cap

interface InitiateResponse {
  document_id: string;
  s3_key: string;
  presigned_put_url: string;
  expires_in_seconds: number;
  max_size_bytes: number;
  content_type: string;
  filename: string;
}

/**
 * Two-step document upload:
 *   1. POST /documents/initiate → backend mints a presigned S3 PUT URL
 *   2. PUT the binary directly to S3 (bypasses API Gateway 10MB cap)
 *
 * Validates type and size client-side before hitting the network.
 *
 * Returns the document_id the agent uses to call
 * extract_policy_from_document. The caller then includes the document_id
 * in the next chat message (chat) or sends a synthetic transcript event
 * (voice) so the agent knows there's a document to extract.
 */
export async function uploadDocument(
  file: File,
  customerId: string | null
): Promise<{ document_id: string; filename: string; content_type: string; size_bytes: number }> {
  // Browsers sometimes report markdown as text/plain or omit content-type
  // entirely. Sniff by extension as a fallback.
  let contentType = file.type || '';
  if (!ALLOWED_DOC_CONTENT_TYPES[contentType]) {
    const ext = file.name.toLowerCase().split('.').pop() || '';
    if (ext === 'md') contentType = 'text/markdown';
    else if (ext === 'txt') contentType = 'text/plain';
    else if (ext === 'pdf') contentType = 'application/pdf';
    else if (ext === 'jpg' || ext === 'jpeg') contentType = 'image/jpeg';
    else if (ext === 'png') contentType = 'image/png';
    else if (ext === 'webp') contentType = 'image/webp';
  }
  if (!ALLOWED_DOC_CONTENT_TYPES[contentType]) {
    throw new Error(`Unsupported file type. Allowed: PDF, Markdown, JPEG, PNG, WEBP.`);
  }
  if (file.size > MAX_DOC_SIZE_BYTES) {
    const limitMb = Math.round(MAX_DOC_SIZE_BYTES / 1024 / 1024);
    throw new Error(`File is too large. Maximum size is ${limitMb} MB.`);
  }

  const initiate = await postJson<InitiateResponse>('documents/initiate', {
    filename: file.name,
    content_type: contentType,
    customer_id: customerId,
  });

  // The presigned URL signs the Content-Type and Content-Length-Range,
  // so we must PUT with the exact same Content-Type the server signed.
  const putResponse = await fetch(initiate.presigned_put_url, {
    method: 'PUT',
    headers: { 'Content-Type': initiate.content_type },
    body: file,
  });
  if (!putResponse.ok) {
    throw new Error(
      `Upload to S3 failed (${putResponse.status}). The presigned URL may have expired.`
    );
  }

  return {
    document_id: initiate.document_id,
    filename: initiate.filename,
    content_type: initiate.content_type,
    size_bytes: file.size,
  };
}
